name: tasking
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.2
  flutter_svg: ^2.0.7
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  icons_launcher: ^2.1.4
  icons_plus: ^4.0.0
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svg/
flutter_intl:
  enabled: true
